---
- hosts: spine
  gather_facts: false

  vars:
   load_operation: merge

  roles:
   - role: arcos-system
     tags: system
   - role: arcos-l3ints
     tags: l3
   - role: arcos-bgp
     tags: bgp
