---
- hosts: arcos rr
  gather_facts: false

  vars:
   load_operation: merge

  roles:
   - role: arcos-system
     tags: system
   - role: arcos-l2vrf
     tags: l2vrf
   - role: arcos-l2ints
     tags: l2ints
   - role: arcos-l3ints
     tags: l3
   - role: arcos-l3vrf
     tags: l3vrf
   - role: arcos-bgp
     tags: bgp
