name: Run Ansible for leaf

on:
  push:
    paths:
      - 'host_vars/leaf1'
      - 'group_vars/**'
      - 'roles/**'
      - 'hosts'
      - 'arcos-config-leaf.yml'
      - '.github/workflows/**'

jobs:
  deploy-leaf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

     # - name: Set up Python
     #   uses: actions/setup-python@v4
     #   with:
     #     python-version: '3.x'

     # - name: Install Ansible
     #   run: |
     #     python -m pip install --upgrade pip
     #     pip install ansible

     # - name: Install Arrcus Collection
     #   run: |
     #     ansible-galaxy collection install arrcus.arcos

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 10.50.101.103 >> ~/.ssh/known_hosts

      - name: SSH and Run Playbook for leaf1 (Check Mode)
        run: |
          ssh -i ~/.ssh/id_rsa serhat@ce-server-3 'echo "Connected!" && cd /local/serhat/ansible-demo/ansible-provision && ansible-playbook -i hosts arcos-config-leaf.yml --limit leaf1 --check --diff'
